import LayoutManager from "@/src/layouts/LayoutManager";
import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "../scss/globals.css";

const roboto = Roboto({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Nextcent",
  description: "Generated by Nextcent",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.className} antialiased`}
        suppressHydrationWarning
      >
        <LayoutManager>{children}</LayoutManager>
      </body>
    </html>
  );
}
